### ISSUE TITLE
Boer South Africa releases English South Africa as a puppet.

### ISSUE THREAD

**Issue by Sillken** [moretrim/ccHFM#119]
If the Boers win the Boer War, they'll have access to the Create South Africa decision, which releases English primary South Africa as a puppet and gives it their entire territory with the exception of their capital.

**Comment by moretrim** [comment]
That decision is not available to countries in Africa. I have however identified British dominion events, which target whoever oversees potential dominion land:

https://github.com/moretrim/ccHFM/blob/60d36039578d346cff9d3ebe0647f0f090024264/ccHFM/events/BritishDominions.txt#L681-L687

This will easily happen to e.g. a Boer republic. Under synthetic conditions:

![Screenshot_20210811_034940](https://user-images.githubusercontent.com/49937701/128957384-497e5412-75c0-4bf6-87c1-e4f926ab07c1.png)

Given that these events remove British cores, restricting them to the United Kingdom/England seems like a good fix. I’m going to leave the issue open for now until we can be confident it’s really been fixed, in case South Africa can appear in different circumstances. A save would be helpful here.

**Comment by moretrim** [comment]
Adding a note that by choosing the above fix this we are diverging from upstream. Might revisit at some later point.
