### ISSUE TITLE
Irregulars aren't enabled by default?

### ISSUE THREAD

**Issue by Jorde5212** [moretrim/ccHFM#135]
Not really a big deal, but for some reason irregulars aren't even an option to build, when they normally are. Playing as Brazil.
![image](https://user-images.githubusercontent.com/81151094/146459714-4d093c71-d155-416c-8948-52d8bac55230.png)

**Comment by moretrim** [comment]
This is an HFM choice, restricting them to (most) uncivs:

https://github.com/moretrim/ccHFM/blob/47becfb5ccb5c1e4786bb500f718b524df991b20/ccHFM/inventions/NNM_inventions.txt#L1-L18

It is not only preserved in the unfinished 1.28 version, [but the restriction has even been extended to more countries.](https://github.com/SighPie/HFM/blob/84f36107bf0dd140f3e442ef363822950eefca04/HFM/inventions/NNM_inventions.txt#L53-L73) Consequently there’s no plan to change that.

Note that HFM also chooses to have extremely cheap irregulars, to allow even the most backward countries to field brigades. Allowing other countries to build irregulars could have unintended consequences. (That being said, cavalry is also extremely cheap for the same reason and is available to all.)
