### ISSUE TITLE
A fix for zombie wars

### ISSUE THREAD

**Issue by rogerburks** [moretrim/ccHFM#84]
The problem: Frequently, tags that stop existing because of events or decisions will be in a war when they stop existing. This can result in a never-ending war with any tags that still exist, because non-existent tags may not automatically white peace. This breaks any content for the involved existing tag that requires peace to occur.

Such a never ending war looks like this:

![image](https://user-images.githubusercontent.com/17787203/118430451-f3619c00-b688-11eb-820c-1c35281c13fb.png)

And on the map it can be seen that Harar and Majeerteen exist, but Shewa and the Shilluk Kingdom do not exist:

![image](https://user-images.githubusercontent.com/17787203/118430569-328fed00-b689-11eb-9b66-338ddf0ef9e8.png)

Proposed solution 1: All events and decisions that annex tags could be adjusted to `end_war` for the tag first. This probably belongs as best practice advice, or someone could laboriously adjust all annexation across the mod to do this.

Proposed solution 2: An event can be created for the ai only, that triggers when it has a war opponent that does not exist:

https://github.com/moretrim/PFH/blob/23e3b0a32b5e819a54eb967c06b16d556b91292b/PFH/events/ZombieWars.txt#L8-L23

I have added a `mean_time_to_happen` of one month for testing purposes, also to help in being aware of when the event triggers and works.

This should be tested to detect any unforeseen negative consequences, such as ending legitimate wars that may briefly have both existing and non-existing countries on the other side.

In the first test, it works:

![image](https://user-images.githubusercontent.com/17787203/118431675-bcd95080-b68b-11eb-8f59-c8babe7a3ea1.png)

**Comment by moretrim** [comment]
I tackled the issue to turn it from an event into a decision. I also decided to handle zombie overlords, which turned out super tricky. So tricky that I want some testing done before merging the change in.

**Comment by moretrim** [comment]
Another case of auto-close not helping: resolved by 2e205e848d1b22e392b390338dedf707ac7b5212.
